### ISSUE TITLE
awtk-linux-fb 和 awtk中目录不匹配。

### ISSUE THREAD

**Issue by Misng** [zlgopen/awtk-linux-fb#1]
我按照**REDAME**中的流程来编译嵌入式Linux平台demo，遇到了编译找不到头文件的问题。好像是**base**的目录缺失。
随之我从**awtk**的文件夹中找到同名的文件，然后将其拷贝到**awtk-port**目录下面，然后编译，虽然出现了一些警告，最后是编译通过。
另外，tslib库，源码目录中没有，我是从github上找到的一份源码进行编译。

第二个问题，我在嵌入式linux下面运行demo1,
fb_info_t: /dev/fb1
fb_info_t: xres=720 yres=576 bits_per_pixel=16 mem_size=829440
fb_info_t: red(10 5) green(5 5) blue(0 5)
line_length=1440 mem_size=829440
xres_virtual =720 yres_virtual=576 xpanstep=1 ywrapstep=0
tslib_thread_run:113 info.ts != NULL
input_thread_run:266 info.fd >= 0
mouse_thread_run:139 info.fd >= 0
Build at: Dec 25 2018 21:00:39
FBIO_WAITFORVSYNC: -1 0
FBIO_WAITFORVSYNC: -1 0
FBIO_WAITFORVSYNC: -1 0
FBIO_WAITFORVSYNC: -1 0
FBIO_WAITFORVSYNC: -1 0
FBIO_WAITFORVSYNC: -1 0
FBIO_WAITFORVSYNC: -1 0
FBIO_WAITFORVSYNC: -1 0
FBIO_WAITFORVSYNC: -1 0

一直重复最后一行的打印。不知道为什么，但在主机Ubuntu16中没有最后一行的打印。
难道是上面拷贝awtk中同名文件的问题造成的吗？

**Comment by xianjimli** [comment]
第一个问题已修改。谢谢。

FBIO_WAITFORVSYNC返回-1，可能是驱动没有实现这个功能，应该没什么问题。

显示正常吗？

**Comment by Misng** [comment]
> 第一个问题已修改。谢谢。
> 
> FBIO_WAITFORVSYNC返回-1，可能是驱动没有实现这个功能，应该没什么问题。
> 
> 显示正常吗？

FBIO_WAITFORVSYNC 这个是用来做什么的？

**Comment by Misng** [comment]
另外，我的鼠标节点感觉有点不一样，设备节点是   /dev/1-2.3  ，杂项设备 /dev/mice
我是不是还需要在什么地方，去指定啊？

**Comment by xianjimli** [comment]
3.编辑awtk-port/main_loop_linux.c修改输入设备的文件名
```
#define FB_DEVICE_FILENAME "/dev/fb0"
#define TS_DEVICE_FILENAME "/dev/input/event0"
#define KB_DEVICE_FILENAME "/dev/input/event1"
```
