### ISSUE TITLE
arm-linux-gnueabihf  build err：awtk-port/tslib_thread.c:25:19: fatal error: tslib.h: No such file or directory

### ISSUE THREAD

**Issue by Engrtao** [zlgopen/awtk-linux-fb#10]
arm-linux-gnueabihf-gcc -o awtk-port/tslib_thread.o -c -std=gnu99 -g -Wall -Os -DHAS_STD_MALLOC -DWITH_FS_RES -DHAS_STDIO -DWITH_VGCANVAS -DWITH_UNICODE_BREAK -DLINUX -DSTBTT_STATIC -DSTB_IMAGE_STATIC -DWITH_STB_IMAGE -DWITH_STB_FONT -DWITH_NANOVG_AGGE -DWITH_WIDGET_TYPE_CHECK -DLINUX -DHAS_PTHREAD -DENABLE_CURSOR -DHAS_TSLIB -I/usr/arm-linux-gnueabihf/include -I/home/ud/v3s/awtk/demo/awtk -I/home/ud/v3s/awtk/demo/awtk/src -I/home/ud/v3s/awtk/demo/awtk/3rd -I/home/ud/v3s/awtk/demo/awtk/src/ext_widgets -I/home/ud/v3s/awtk/demo/awtk/tools -I/home/ud/v3s/awtk/demo/awtk/3rd/agge -I/home/ud/v3s/awtk/demo/awtk/3rd/agg/include -I/home/ud/v3s/awtk/demo/awtk/3rd/nanovg -I/home/ud/v3s/awtk/demo/awtk/3rd/nanovg/base -I/home/ud/v3s/awtk/demo/awtk/3rd/libunibreak -I/home/ud/v3s/awtk/demo/awtk/3rd/gpinyin/include awtk-port/tslib_thread.c
awtk-port/tslib_thread.c:25:19: fatal error: tslib.h: No such file or directory
compilation terminated.
scons: *** [awtk-port/tslib_thread.o] Error 1
scons: building terminated because of errors.

**Comment by xianjimli** [comment]
tslib需要自己下载或使用预先编译的。

**Comment by kent52712** [comment]
可以修改awtk_config.py 不编译tslib就OK了
TSLIB_LIB_DIR=''
TSLIB_INC_DIR=''

**Comment by YinWenshuo** [comment]
遇到同样的问题，看了这个issue，解决了，谢谢。
