### ISSUE TITLE
scons 交叉编译Renesas平台出现了链接错误，有没有大哥知道咋回事

### ISSUE THREAD

**Issue by macdovellrong** [zlgopen/awtk-linux-fb#106]
/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc -o bin/demo1 -Wl,-rpath=./bin -Wl,-rpath=./ build/var/awtk/demos/demo1_app.o -Llib -Lbin -L/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/aarch64-poky-linux/usr/lib -L/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/aarch64-poky-linux/lib -L/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/aarch64-poky-linux/usr/lib/aarch64-poky-linux/9.3.0 -lassets_old -lawtk_global -lfscript_ext_widgets -lextwidgets -lwidgets -lawtk_linux_fb -lbase -lgpinyin -llinebreak -lfribidi -ldebugger -lfscript_ext -lstreams -lconf_io -lhal -lxml -lcharset -lcsv -lubjson -lcompressors -lminiz -ltkc_core -lmbedtls -lnanovg-agge -lagge -lnanovg -lstdc++ -lpthread -lrt -lm -ldl
/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/real-ld: cannot find Scrt1.o: No such file or directory
/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/real-ld: cannot find crti.o: No such file or directory
/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/real-ld: cannot find crtbeginS.o: No such file or directory
/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/real-ld: cannot find /lib/libc.so.6
/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/real-ld: cannot find /usr/lib/libc_nonshared.a
/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.3.0/real-ld: cannot find /lib/ld-linux-aarch64.so.1

头文件目录和库文件目录都设置了
TOOLS_PREFIX='/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-'
OS_CPPPATH += ['/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/aarch64-poky-linux/usr/include/']
OS_CPPPATH += ['/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/aarch64-poky-linux/usr/include/c++/9.3.0/']
OS_CPPPATH += ['/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/aarch64-poky-linux/usr/include/c++/9.3.0/aarch64-poky-linux/']

OS_LIBPATH += ['/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/aarch64-poky-linux/usr/lib/']
OS_LIBPATH += ['/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/aarch64-poky-linux/lib/']
OS_LIBPATH += ['/home/gzh/Renesas/rcar-xos/v2.18.0/tools/toolchains/poky/sysroots/aarch64-poky-linux/usr/lib/aarch64-poky-linux/9.3.0/']

**Comment by xianjimli** [comment]
感觉是工具链的问题。

**Comment by macdovellrong** [comment]
> 感觉是工具链的问题。

需要在awtk_config.py设置CCFLAGS和LINKFLAGS的 --sysroot路径
