### ISSUE TITLE
run ./release/bin/demoui err:assets_manager.c:122

### ISSUE THREAD

**Issue by Engrtao** [zlgopen/awtk-linux-fb#12]
# ./release/bin/demoui
app_root_is_valid:43 app_root != NULL
try /mnt/sda1
try /mnt/sda1/release/bin
app_root=/mnt/sda1/release
fb_info_t: /dev/fb0
fb_info_t: xres=320 yres=240 bits_per_pixel=16 mem_size=153600
fb_info_t: red(11 5) green(5 6) blue(0 5)
line_length=640 mem_size=153600 smem_len=153600
xres_virtual =320 yres_virtual=240 xpanstep=0 ywrapstep=0
ratio=1.000000 320 240
mouse_thread_run:139 info.fd >= 0
Build at: Aug  9 2019 00:52:50
fs_os_get_file_size:177 stat(name, &st) == 0
fs_file_create:92 fp != NULL
demoui: build/var/awtk/src/base/assets_manager.c:122: load_asset: Assertion `file_read_part(path, info->data, size, 0) == size' failed.
Aborted

**Comment by xianjimli** [comment]
你更新代码试试。谢谢

**Comment by Engrtao** [comment]
> 你更新代码试试。谢谢

确实可以
