### ISSUE TITLE
arm-linux移植编译问题请教

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk-linux-fb#15]
TSLIB_LIB_DIR='/opt/28x/tslib/lib'
TSLIB_INC_DIR='/opt/28x/tslib/include'
TOOLS_PREFIX='/opt/28x/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/bin/arm-linux-'

编译器是需要下载吗？用我手上现有的ARM-linux编译器编译不过

**Comment by xianjimli** [comment]
用你开发板配套的工具链。遇到什么问题，把编译log贴上来。
