### ISSUE TITLE
树莓派交叉编译的时候出错

### ISSUE THREAD

**Issue by renyongjian** [zlgopen/awtk-linux-fb#16]
/opt/raspberry_tool/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc -o build/var/awtk/src/base/widget.o -c -std=gnu99 -g -Wall -Os -DHAS_STD_MALLOC -DWITH_FS_RES -DHAS_STDIO -DWITH_VGCANVAS -DWITH_UNICODE_BREAK -DLINUX -DSTBTT_STATIC -DSTB_IMAGE_STATIC -DWITH_STB_IMAGE -DWITH_STB_FONT -DWITH_NANOVG_AGGE -DWITH_WIDGET_TYPE_CHECK -DLINUX -DHAS_PTHREAD -DENABLE_CURSOR -DHAS_TSLIB -I/opt/raspberry_tool/tslib/include -I/home/renyj/work/awtk/awtk -I/home/renyj/work/awtk/awtk/src -I/home/renyj/work/awtk/awtk/3rd -I/home/renyj/work/awtk/awtk/src/ext_widgets -I/home/renyj/work/awtk/awtk/tools -I/home/renyj/work/awtk/awtk/3rd/agge -I/home/renyj/work/awtk/awtk/3rd/agg/include -I/home/renyj/work/awtk/awtk/3rd/nanovg -I/home/renyj/work/awtk/awtk/3rd/nanovg/base -I/home/renyj/work/awtk/awtk/3rd/libunibreak -I/home/renyj/work/awtk/awtk/3rd/gpinyin/include build/var/awtk/src/base/widget.c
build/var/awtk/src/base/widget.c: In function 'widget_draw_icon_text':
build/var/awtk/src/base/widget.c:937:1: internal compiler error: Segmentation fault
 }
 ^
no stack trace because unwind library not available
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.launchpad.net/gcc-linaro> for instructions.
scons: *** [build/var/awtk/src/base/widget.o] Error 1
scons: building terminated because of errors.

使用交叉编译器是
https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin。

使能了TSlib之后出问题。

**Comment by renyongjian** [comment]
https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-bcm2708-linux-gnueabi
刚刚试了试使用和它在同一个目录的这个编译器。编译正常通过。

**Comment by soyzhc** [comment]
编译器自己崩溃了，感觉是编译器有问题，升级编译器版本看看

另外你是在 awtk-linux-fb 目录编译， 还是直接在 awtk目录编译的?

**Comment by renyongjian** [comment]
在 awtk-linux-fb，编译的。
我使用和它同一个目录的另外一个交叉编译工具链可以编译通过。
看到一个博客说，我用的那个编译器有问题。可能那个编译器真的有问题。
