### ISSUE TITLE
在荔枝派上demoui占用CPU97%

### ISSUE THREAD

**Issue by Engrtao** [zlgopen/awtk-linux-fb#18]
在荔枝派上demoui占用CPU 97%，开启浮点数，渲染使用AGGE

**Comment by xianjimli** [comment]
我不了解荔枝派。荔枝派是什么样的配置？CPU、FLASH、RAM和LCD大小

**Comment by Engrtao** [comment]
The V3s processor represents Allwinner’s latest achievement in video
encoding processors, which integrates a single
ARM CortexTM-A7 CPU that operates at speed up to 1.2GHz with supporting
numerous peripherals. The processor
targets the need of the growing Car Digital Video Record (DVR) and IP
Camera (IPC) Monitor System.
A 512Mbit DDR2 is highly integrated in the V3s, in addition the V3s has
optimized external memory interfaces to SPI
NAND /Nor flash, SD/MMC.
Dedicated video engine is included to provide an advanced multimedia
applications and services. Video Engine supports
multi-format such as H.264 encoder by 720p@60fps, H.264 decoder by
1080p@30fps, JPEG/MJPEG decoder by
1080p@30fps. To enrich camera feature, V3s equips an 8M HawkViewTM ISP with
advanced features like spatial
de-noise, chrominance de-noise, zone-based AE/AF/AWB statistics, black
level correction, lens shading correction, color
correction and anti-flick detection statistics.
To reduce total system cost and enhance overall functionality ,V3s has some
popular hardware peripherals such as UART,
SPI, USB HS/FS OTG , TWI etc.


DS ：
https://whycan.cn/files/members/1808/Allwinner_V3s_User_Manual_V1_0_20190820-1651.pdf


jim <notifications@github.com> 于2019年8月20日周二 上午10:41写道：

**Comment by soyzhc** [comment]
用最新的版本试试
