### ISSUE TITLE
awtk-linux-fb移植编译错误

### ISSUE THREAD

**Issue by linzy2256** [zlgopen/awtk-linux-fb#19]
按照移植说明文档步骤下载代码，编译tslib。在linux-fb目录下运行scons编译提示错误。log如下：
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo_main.c:54: undefined reference to `tk_atoi'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo_main.c:57: undefined reference to `tk_atoi'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo_main.c:88: undefined reference to `system_info'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo_main.c:88: undefined reference to `system_info_set_default_font'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo_main.c:96: undefined reference to `window_manager'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo_main.c:96: undefined reference to `window_manager_set_cursor'
build/var/awtk/demos/demo1_app.o: In function `on_show_dialog':
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:45: undefined reference to `dialog_create_simple'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:46: undefined reference to `dialog_cast'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:48: undefined reference to `widget_set_text'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:50: undefined reference to `button_create'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:51: undefined reference to `widget_set_text'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:53: undefined reference to `button_create'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:54: undefined reference to `widget_set_text'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:56: undefined reference to `label_create'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:57: undefined reference to `widget_set_text'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:59: undefined reference to `widget_on'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:60: undefined reference to `widget_on'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:62: undefined reference to `dialog_modal'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/demo1_app.c:66: undefined reference to `tk_mem_dump'
build/var/awtk/demos/demo1_app.o: In function `on_cancel':
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/common.inc:45: undefined reference to `dialog_quit'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/common.inc:47: undefined reference to `tk_mem_dump'
build/var/awtk/demos/demo1_app.o: In function `on_ok':
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/common.inc:30: undefined reference to `dialog_quit'
/home/mcu/linzy/WH6X/awtk/awtk-linux-fb/build/var/awtk/demos/common.inc:32: undefined reference to `tk_mem_dump'

**Comment by xianjimli** [comment]
麻烦更新一下代码。

**Comment by linzy2256** [comment]
重新下载编译正常。谢谢
