### ISSUE TITLE
鼠标要在程序运行后插入，才能使用

### ISSUE THREAD

**Issue by Misng** [zlgopen/awtk-linux-fb#2]
我按照你上一个问题中的回复，修改了 TS_DEVICE_FILENAME  变量的值。
在板端运行 demo1时，出现发生崩溃。程序出现结果如下
![image](https://user-images.githubusercontent.com/16435001/50532781-450d3880-0b59-11e9-9f87-554eba9b74f4.png)
在一个偶然的机会下，我在拔掉鼠标设备后运行程序，程序运行正常。
![image](https://user-images.githubusercontent.com/16435001/50532786-6c640580-0b59-11e9-9504-f31dc12ebc26.png)
然后我再把鼠标插入，就看到鼠标了。鼠标可以移动。
请问，为什么会出现这样的情况。

我的鼠标是通过USB接口和板子相连接。
我尝试过 修改变量 TS_DEVICE_FILENAME  为 /dev/event0 或者  /dev/mouse0 都出现了上述的问题。期间还使用 scons -c 清除，再使用 scons 编译，运行。

**Comment by Misng** [comment]
![image](https://user-images.githubusercontent.com/16435001/50592292-7de93c80-0ece-11e9-867b-0c384240c891.png)


使用 input_test 没有问题。可以扑捉到鼠标的操作。但使用demo1还和上面一样。╮(╯▽╰)╭

**Comment by xianjimli** [comment]
在虚拟器里吗？调试一下，看崩在哪里

**Comment by Misng** [comment]
程序在板端上运行的，我初步猜想，可能是tslib配置的问题，后来我注释了awtk-port/main_loop_linux.c文件中关于TSLIB的代码后，程序运行就正常了。

![image](https://user-images.githubusercontent.com/16435001/50638828-18628200-0f9a-11e9-9caa-0ed5a3d1b587.png)

以下是程序的运行截图
![image](https://user-images.githubusercontent.com/16435001/50639054-e6055480-0f9a-11e9-9e93-42e1d368a414.png)

一个疑问是：我屏蔽的那块代码是否会影响到其它功能。

**Comment by xianjimli** [comment]
那可能是tslib的问题，我用的tslib是厂家预先编译好的。去掉tslib不会有其它问题。
