### ISSUE TITLE
海思嵌入式平台demoui运行报Segmentation fault

### ISSUE THREAD

**Issue by kent52712** [zlgopen/awtk-linux-fb#21]
跟踪代码发现在fb_open函数
  if(fb_is_2fb(fb)) {
    fb->fbmem1 = fb->fbmem0 + size;
    memset(fb->fbmem1, 0xff, size);//此行导致了段错误
  }

**Comment by xianjimli** [comment]
具体情况不清楚，你按下面的方法试试：
1.用root用户运行。
2.fb_is_2fb检测出支持2fb的，看看驱动是不是正确实现了2fb。
3.让fb_is_2fb返回FALSE。

**Comment by kent52712** [comment]
> 具体情况不清楚，你按下面的方法试试：
> 1.用root用户运行。
> 2.fb_is_2fb检测出支持2fb的，看看驱动是不是正确实现了2fb。
> 3.让fb_is_2fb返回FALSE。
您好，使fb_is_2fb返回false后，执行结果：
# ./demoui 
app_root_is_valid:43 app_root != NULL
try /home/stb/bin
app_root=/home/stb
fb_info_t: /dev/fb0
fb_info_t: xres=1920 yres=1080 bits_per_pixel=32 mem_size=8294400
fb_info_t: red(16 8) green(8 8) blue(0 8)
line_length=7680 mem_size=8294400 smem_len=16588800
xres_virtual =1920 yres_virtual=2160 xpanstep=1 ywrapstep=0
ratio=1.000000 1920 1080
Build at: Sep 17 2019 17:27:23
input_dispatch_one_event:150 keyboard read failed(ret=-1, errno=0)
input_dispatch_one_event:154 keyboard read failed(ret=-1, errno=0, fd=-1, filename=/dev/input/event1)
Print keyboard: : Success
window preload open
FBIOPAN_DISPLAY ret=0 yoffset=1080
Segmentation fault

**Comment by kent52712** [comment]
> 具体情况不清楚，你按下面的方法试试：
> 1.用root用户运行。
> 2.fb_is_2fb检测出支持2fb的，看看驱动是不是正确实现了2fb。
> 3.让fb_is_2fb返回FALSE。

您好，经测试，将fb_open中fb->fbmem0 = (uint8_t*)mmap(0, fb->fix.smem_len, PROT_READ | PROT_WRITE, MAP_SHARED, fb->fd, 0);  第二个参数size改为 fb->fix.smem_len就运行正常了，
其中size=8294400   smem_len=16588800
