### ISSUE TITLE
如修改鼠标的当前位置到鼠标图片的左上角？

### ISSUE THREAD

**Issue by YinWenshuo** [zlgopen/awtk-linux-fb#25]
我看文档说明提到过 "为了简化处理，在绘制指针时，我们把图片的中心定位到鼠标的当前位置",请问如何修改鼠标的当前位置到鼠标图片的左上角，因为我们的鼠标一般是一个箭头朝左上角的图片，所以，我认为把鼠标的当前位置定位在鼠标图片的左上角更合理一些。

**Comment by YinWenshuo** [comment]
@xianjimli 讨教一下

**Comment by xianjimli** [comment]
为了简化处理。鼠标指针用得比较少，改下图片就行了，暂时先这样吧。
