### ISSUE TITLE
在使用龙芯的编译器编译的时候，编译不过提示awtk库有问题

### ISSUE THREAD

**Issue by xiaodingding** [zlgopen/awtk-linux-fb#32]
/opt/gcc-4.3-ls232-softfloat/bin/mipsel-linux-gcc -o build/var/awtk/src/native_window/native_window_raw.o -c -std=gnu99 -Wall -Os -DHAS_STD_MALLOC -DWITH_FS_RES -DHAS_STDIO -DWITH_VGCANVAS -DWITH_UNICODE_BREAK -DLINUX -DSTBTT_STATIC -DSTB_IMAGE_STATIC -DWITH_STB_IMAGE -DWITH_STB_FONT -DWITH_NANOVG_AGGE -DWITH_WIDGET_TYPE_CHECK -DLINUX -DHAS_PTHREAD -DENABLE_CURSOR -DHAS_TSLIB -I/home/dwx/src/tslib/include -I/home/dwx/src/zlgopen/awtk -I/home/dwx/src/zlgopen/awtk/src -I/home/dwx/src/zlgopen/awtk/3rd -I/home/dwx/src/zlgopen/awtk/src/ext_widgets -I/home/dwx/src/zlgopen/awtk/tools -I/home/dwx/src/zlgopen/awtk/3rd/agge -I/home/dwx/src/zlgopen/awtk/3rd/agg/include -I/home/dwx/src/zlgopen/awtk/3rd/nanovg -I/home/dwx/src/zlgopen/awtk/3rd/nanovg/base -I/home/dwx/src/zlgopen/awtk/3rd/libunibreak -I/home/dwx/src/zlgopen/awtk/3rd/gpinyin/include build/var/awtk/src/native_window/native_window_raw.c
build/var/awtk/src/native_window/native_window_raw.c: In function 'native_window_create':
build/var/awtk/src/native_window/native_window_raw.c:115: warning: implicit declaration of function 'widget_set_prop_pointer'
build/var/awtk/src/native_window/native_window_raw.c:115: error: 'WIDGET_PROP_NATIVE_WINDOW' undeclared (first use in this function)
build/var/awtk/src/native_window/native_window_raw.c:115: error: (Each undeclared identifier is reported only once
build/var/awtk/src/native_window/native_window_raw.c:115: error: for each function it appears in.)
scons: *** [build/var/awtk/src/native_window/native_window_raw.o] Error 1

**Comment by xiaodingding** [comment]
已解决，在native_window_raw.h文件里面加上#include "base/widget_consts.h"，这句话就可以了。

**Comment by xianjimli** [comment]
好的，谢谢。
