### ISSUE TITLE
运行demoui后白屏

### ISSUE THREAD

**Issue by Nicofan-1988** [zlgopen/awtk-linux-fb#33]
根据教程移植后，运行demoui后显示白屏。屏幕分辩率是1026*600。log如下，到这就不动了。
/ # ./release/bin/demoui
app_root_is_valid:43 app_root != NULL
try /
try /release/bin
app_root=/release
fb_info_t: /dev/fb0
xres=1024 yres=600
xres_virtual=1024 yres_virtual=600
bits_per_pixel=32 line_length=4096
fb_info_t: red(16 8) green(8 8) blue(0 8)
xpanstep=0 ywrapstep=1
fb_size=2457600 fb_total_size=33554432 fb_nr=1 smem_len=33554432
fb_open clear
fb_open ok
ratio=1.000000 1024 600
fec 20b4000.ethernet eth0: Link is Down
random: nonblocking pool is initialized
nfs: server 192.168.0.5 not responding, still trying

**Comment by xianjimli** [comment]
```
log_set_log_level(LOG_LEVEL_DEBUG);
```
把完整的 log 打印处理看看。

**Comment by Nicofan-1988** [comment]
Please press Enter to activate this console.
/ # cd lib/modules/4.1.15
/lib/modules/4.1.15 # ls
QWebBrowser     release         release.tar.gz
/lib/modules/4.1.15 # ./release/bin/demoui
app_root_is_valid:43 app_root != NULL
try /lib/modules/4.1.15
try /lib/modules/4.1.15/release/bin
app_root=/lib/modules/4.1.15/release
fb_info_t: /dev/fb0
xres=1024 yres=600
xres_virtual=1024 yres_virtual=600
bits_per_pixel=32 line_length=4096
fb_info_t: red(16 8) green(8 8) blue(0 8)
xpanstep=0 ywrapstep=1
fb_size=2457600 fb_total_size=33554432 fb_nr=1 smem_len=33554432
fb_open clear
fb_open ok
ratio=1.000000 1024 600
fec 20b4000.ethernet eth0: Link is Down
random: nonblocking pool is initialized
nfs: server 192.168.0.5 not responding, still trying

这个就是运行后的log。

---原始邮件---
发件人:"jim"<notifications@github.com>;
发送时间:2020年3月12日(星期四) 晚上9:13
收件人:"zlgopen/awtk-linux-fb"<awtk-linux-fb@noreply.github.com>;
抄送人:"Nicofan-1988"<603238571@qq.com>;"Author"<author@noreply.github.com>;
主题:Re: [zlgopen/awtk-linux-fb] 运行demoui后白屏 (#33)



 log_set_log_level(LOG_LEVEL_DEBUG);  
把完整的 log 打出来看看。
 
&mdash;

**Comment by xianjimli** [comment]
资源放在nfs上的吗？

**Comment by Nicofan-1988** [comment]
稍等，你说的资源是指awtk那个文件夹吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jim"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月13日(星期五) 晚上9:06
收件人:&nbsp;"zlgopen/awtk-linux-fb"<awtk-linux-fb@noreply.github.com&gt;;
抄送:&nbsp;"步之道"<603238571@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zlgopen/awtk-linux-fb] 运行demoui后白屏 (#33)





 
资源放在nfs上的吗？

**Comment by Nicofan-1988** [comment]
是的，用busybox构建的文件系统，通过nfs挂载




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jim"<notifications@github.com&gt;; 
发送时间: 2020年3月13日(星期五) 晚上9:06
收件人: "awtk-linux-fb"<awtk-linux-fb@noreply.github.com&gt;; 
抄送: "步之道"<603238571@qq.com&gt;; "author"<author@noreply.github.com&gt;; 
主题: Re: [zlgopen/awtk-linux-fb] 运行demoui后白屏 (#33)





 
资源放在nfs上的吗？

**Comment by xianjimli** [comment]
感觉资源没加载成功，你不用nfs试试。

**Comment by Nicofan-1988** [comment]
只要用nfs挂载文件系统，运行demoui就会出现白屏，下载到板子上通过emmc启动能够正常运行。能帮忙分析一下可能是什么原因吗？

**Comment by Nicofan-1988** [comment]
![image](https://user-images.githubusercontent.com/54854982/76697047-18493080-66cd-11ea-8f91-868ff7194665.png)
正常运行后，一段时间不操作会自己切换到那个有很多小火花的界面，然后一直输出途中的打印信息，点一下屏幕然后就正常了。
请问这个有可能是什么问题？

**Comment by soyzhc** [comment]
这个是正常的, demoui故意做的, 模拟动画资源不存在的情况
