### ISSUE TITLE
海思平台编译报错

### ISSUE THREAD

**Issue by duduathz** [zlgopen/awtk-linux-fb#35]
海思平台编译出现如下错误。
scons: Reading SConscript files ...
KeyError: 'GRAPHIC_BUFFER':
  File "/home/du/AWTK/awtk-v1.3/awtk-linux-fb/SConstruct", line 45:
    SConscript(SConscriptFiles)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File "/home/du/AWTK/awtk-v1.3/awtk-linux-fb/build/var/awtk/src/SConscript", line 9:
    GRAPHIC_BUFFER = os.environ['GRAPHIC_BUFFER'];
  File "/usr/lib/python2.7/UserDict.py", line 40:
    raise KeyError(key)
请问可能是何种原因引起的？
谢谢！

**Comment by xianjimli** [comment]
awtk-linux-fb和awtk都用最新的吧。

**Comment by duduathz** [comment]
是的，应该是tslib的问题。

**Comment by duduathz** [comment]
> awtk-linux-fb和awtk都用最新的吧。

定位到tslib的问题，添加include与lib也不行，在编译脚本中去掉了tslib，编译还是有错误，请问如何去掉tslib？项目上不需要ts功能。

**Comment by xianjimli** [comment]
看不出与ts有关系啊

**Comment by xianjimli** [comment]
把toolchain发给我试试

**Comment by duduathz** [comment]
链接：https://pan.baidu.com/s/1SQxFF7LItkDNjZA_9SJa4Q 
提取码：ncvi
链接：https://pan.baidu.com/s/1eJFpwRKp3R_L2-8O2aJgPA 
提取码：wa1c
有问题加我微信hifine_du.
arm-himix200-linux-为基于 32bit 操作系统 glibc
的工具链。
安装步骤如下：
步骤 1 解压工具链。
执行如下命令进行解压：
tar –xvf arm-himix200-linux.tgz 
步骤 2 安装工具链。
运行命令 sudo ./arm-himix200-linux.install 即可完成此工具链的安装。
其它工具链安装方法与上述描述类似。

**Comment by soyzhc** [comment]
我在Ubuntu16.04试了你的工具链,可以编译成功的

把awtk和awtk-linux-fb 都放在同一级目录下
修改 awtk-linux-fb/awtk_config.py
```
#for prebuild tslib
TSLIB_LIB_DIR=''
TSLIB_INC_DIR=''
TOOLS_PREFIX='/opt/hisi-linux/x86-arm/arm-himix200-linux/bin/arm-himix200-linux-'
```
然后进入awtk-linux-fb编译
```
cd awtk-linux-fb
scons
```

**Comment by duduathz** [comment]
> 我在Ubuntu16.04试了你的工具链,可以编译成功的
> 
> 把awtk和awtk-linux-fb 都放在同一级目录下
> 修改 awtk-linux-fb/awtk_config.py
> 
> ```
> #for prebuild tslib
> TSLIB_LIB_DIR=''
> TSLIB_INC_DIR=''
> TOOLS_PREFIX='/opt/hisi-linux/x86-arm/arm-himix200-linux/bin/arm-himix200-linux-'
> ```
> 
> 然后进入awtk-linux-fb编译
> 
> ```
> cd awtk-linux-fb
> scons
> ```
> 
> 如果还有问题你可以尝试删除awtk-linux-fb, 重新clone一份, 再执行上面的步骤

已经编译通过，之前是百度网盘里下载文件，可能有些问题，githhub上clone下载的可以。
非常感谢！

**Comment by xianjimli** [comment]
好的。我还没下完:(

**Comment by duduathz** [comment]
嗯，之前就是为了省事从百度盘里取的，欲速则不达啊！
