### ISSUE TITLE
更新最新的linux-fb编译不过

### ISSUE THREAD

**Issue by WeSrc-Yin** [zlgopen/awtk-linux-fb#48]
更新最新的linux-fb编译不过
======================== build app ========================
cd ../awtk-aps-p81 && scons LINUX_FB=true
scons: Reading SConscript files ...
MACH=x86_64 ARCH=('64bit', 'ELF') TARGET_ARCH=
TK_ROOT: /home/work/work2020/Progress/UI/awtk
scons: done reading SConscript files.
scons: Building targets ...

src/main.o: In function `main':
/home/work/work2020/Progress/UI/awtk-app/src/main.c:64: undefined reference to `eventhub_init'

eventhub_init是第三方库的函数，

我在awtk_config.py文件里面有加入
OS_LIBPATH=[joinPath(TK_LINUX_FB_ROOT, '../../Libs/')]

每次awtk较大的更新，都会编译不过，感觉awtk的更新还是不够兼容性。’

**Comment by WeSrc-Yin** [comment]
os.environ['TOOLS_NAME'] = '';

这是干嘛的

**Comment by xianjimli** [comment]
写了一个文档，你参考一下：https://github.com/zlgopen/awtk/blob/master/docs/how_to_use_3rd_libs.md

**Comment by xianjimli** [comment]
> os.environ['TOOLS_NAME'] = '';
> 
> 这是干嘛的

这个是windows用来区分mingw和vc的。所有linux下设置为空。

**Comment by WeSrc-Yin** [comment]
可以了，主要是把examples.v2里面的demo里的scripts文件夹和Sconstruct文件拷贝到自己的应用目录下就可以了。

**Comment by WeSrc-Yin** [comment]
可以了，主要是把examples.v2里面的demo里的scripts文件夹和Sconstruct文件拷贝到自己的应用目录下就可以了。
