### ISSUE TITLE
执行xml_to_ui生成的bin文件不可用

### ISSUE THREAD

**Issue by qlu1234** [zlgopen/awtk-linux-fb#5]
xml_to_ui是通过交叉工具链编译的，写了一个简单的mywindow1.xml文件，内容如下:
<window anim_hint=“htranslate”>
  <button style=“red_btn” x=“c” y=“50” w=“128” h=“30” text=“Text”/>
</window>

代码中调用window_open(“mywindow1”);打开，显示黑屏，报错如下：
ui_loader_load_default：36 magic== UI_DATA_MAGIC

**Comment by xianjimli** [comment]
下午我看看。

**Comment by xianjimli** [comment]
要加参数**bin**，否则生成的C代码。

```
[root@M28x release]# ./bin/xml_to_ui                     
Usage: ./bin/xml_to_ui in_filename out_filename [bin]
```

示例：
```
[root@M28x release]# ./bin/xml_to_ui test/b.xml b.bin bin
[root@M28x release]# ls -l b.bin 
-rw-------    1 root     root           279 Jan  1 00:19 b.bin
[root@M28x release]# ./bin/preview_ui b.bin 
```
