### ISSUE TITLE
编译报错 e->event.size = sizeof(e->key_event);

### ISSUE THREAD

**Issue by huohongpeng** [zlgopen/awtk-linux-fb#53]
**没有看到 event_t中有size成员**
`main_loop_t* l = (main_loop_t*)ctx;
  event_queue_req_t event = *evt;
  event_queue_req_t* e = &event;

  if (l != NULL && l->queue_event != NULL) {
    switch (e->event.type) {
      case EVT_KEY_DOWN:
      case EVT_KEY_UP:
      case EVT_KEY_LONG_PRESS: {
        e->event.size = sizeof(e->key_event);
        break;
      }
      case EVT_POINTER_DOWN:
      case EVT_POINTER_MOVE:
      case EVT_POINTER_UP: {
        e->event.size = sizeof(e->pointer_event);
        break;
      }
      case EVT_WHEEL: {
        e->event.size = sizeof(e->wheel_event);
        break;
      }
      default:
        break;
    }
`

**Comment by xianjimli** [comment]
size加了很久了啊：https://github.com/zlgopen/awtk/blob/master/src/tkc/event.h

**Comment by huohongpeng** [comment]
感谢李工回复，我clone的是1.5版本，不是最新的，1.5里没有size，刚从minigui转过来的，看了两天AWTK，太牛了，还不太熟悉，以后好好学习。
