### ISSUE TITLE
awtk-mvvm移植问题

### ISSUE THREAD

**Issue by zxc3489** [zlgopen/awtk-linux-fb#54]
你好，请问基于awtk-mvvm建立的工程如何移植到嵌入式系统上呢?

**Comment by xianjimli** [comment]
请参考这个项目和里面的文档：
https://github.com/zlgopen/awtk-stm32h743iitx-mvvm

**Comment by zxc3489** [comment]
我参考https://github.com/zlgopen/awtk-linux-fb为我的开发板编译一个demo，在awtk-linux-fb中，指定了TOOLS_PREFIX。执行scons APP=../awtk-examples/HelloWorld.Xml-Demo，在编译demo之前，都是用的我指定的工具链，在build app时，使用了系统的gcc，请问还需要在APP对应路径下指定工具链吗？？相关编译详情如下:

`/root/rk3308/rk3308_linux_release/prebuilts/gcc/linux-x86/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ar rc build/lib/libcjson.a build/var/awtk/3rd/cjson/cJSON.o build/var/awtk/3rd/cjson/cJSON_Utils.o
/root/rk3308/rk3308_linux_release/prebuilts/gcc/linux-x86/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ranlib build/lib/libcjson.a
scons: done building targets.
======================== build app ========================
cd ../awtk-examples/HelloWorld.Xml-Demo && scons LINUX_FB=true LCD=240_320
scons: Reading SConscript files ...
MACH=x86_64 ARCH=('64bit', 'ELF') TARGET_ARCH=
TK_ROOT: /root/rk3308/rk3308_linux_release/awtk/awtk
scons: done reading SConscript files.
scons: Building targets ...
gcc -o bin/demo -Wl,-rpath=/root/rk3308/rk3308_linux_release/awtk/awtk/lib src/app_main.o src/window_main.o -Llib -L/root/rk3308/rk3308_linux_release/awtk/awtk/lib -L/root/rk3308/rk3308_linux_release/awtk/awtk/bin -lawtk_global -lextwidgets -lwidgets -lbase -lgpinyin -lstreams -lconf_io -lubjson -lcompressors -lfribidi -lminiz -ltkc_static -llinebreak -lnanovg -lSDL2 -lglad -lGL -lgtk-3 -lgdk-3 -lXext -lX11 -lsndio -lstdc++ -lpthread -lm -ldl -lasound`

**Comment by zxc3489** [comment]
我参考 https://github.com/zlgopen/awtk-linux-fb 为我的开发板编译一个demo，在awtk-linux-fb中，指定了TOOLS_PREFIX。执行scons APP=../awtk-examples/HelloWorld.Xml-Demo，在编译app之前，都是用的我指定的工具链，在build app时，使用了系统的gcc，请问还需要在APP对应路径下指定工具链吗？？相关编译详情如下:

**/root/rk3308/rk3308_linux_release/prebuilts/gcc/linux-x86/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ar** rc build/lib/libcjson.a build/var/awtk/3rd/cjson/cJSON.o build/var/awtk/3rd/cjson/cJSON_Utils.o /root/rk3308/rk3308_linux_release/prebuilts/gcc/linux-x86/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ranlib build/lib/libcjson.a scons: done building targets.
 ======================== build app ========================
cd ../awtk-examples/HelloWorld.Xml-Demo && scons LINUX_FB=true LCD=240_320
scons: Reading SConscript files ... MACH=x86_64 ARCH=('64bit', 'ELF') TARGET_ARCH= TK_ROOT: /root/rk3308/rk3308_linux_release/awtk/awtk scons: done reading SConscript files. scons: Building targets ... 
**gcc** -o bin/demo -Wl,-rpath=/root/rk3308/rk3308_linux_release/awtk/awtk/lib src/app_main.o src/window_main.o -Llib -L/root/rk3308/rk3308_linux_release/awtk/awtk/lib -L/root/rk3308/rk3308_linux_release/awtk/awtk/bin -lawtk_global -lextwidgets -lwidgets -lbase -lgpinyin -lstreams -lconf_io -lubjson -lcompressors -lfribidi -lminiz -ltkc_static -llinebreak -lnanovg -lSDL2 -lglad -lGL -lgtk-3 -lgdk-3 -lXext -lX11 -lsndio -lstdc++ -lpthread -lm -ldl -lasound

**Comment by zxc3489** [comment]
我已经将我的项目成功编译了一个release版本，但是现在的情况是release打包解压后，release文件夹需要占用44M的空间，我的设备上并没有如此多的剩余空间，请问有哪些手段能有效的裁剪不必要的资源文件呢？

**Comment by zxc3489** [comment]
> 我已经将我的项目成功编译了一个release版本，但是现在的情况是release打包解压后，release文件夹需要占用44M的空间，我的设备上并没有如此多的剩余空间，请问有哪些手段能有效的裁剪不必要的资源文件呢？

release中的所有文件都是必须的吗？还是只需要吧release/bin/中的文件打包到设备上呢？

**Comment by zxc3489** [comment]
> > 我已经将我的项目成功编译了一个release版本，但是现在的情况是release打包解压后，release文件夹需要占用44M的空间，我的设备上并没有如此多的剩余空间，请问有哪些手段能有效的裁剪不必要的资源文件呢？
> 
> release中的所有文件都是必须的吗？还是只需要吧release/bin/中的文件打包到设备上呢？

release中有部分是之前在pc上调试编译的so，在对应目录下删除后，就不再打包到release中了，现在板子也成功点亮了，谢谢你们的帮助。
