### ISSUE TITLE
工程编译后在ZMP1107_EVB评估板执行报错

### ISSUE THREAD

**Issue by ZIKEER** [zlgopen/awtk-linux-fb#58]
报错内容为
./demo: awtk-port/lcd_linux/lcd_linux_fb.c: 173: lcd_linux_create_flushable: Assertion `!"not supported framebuffer format."' failed.
请问是哪一步有问题么 评估板的文档的awtk-linux-fb需要git patch，但是版本为1.4.1，请问新的版本需要怎么操作呢

**Comment by WNsACE** [comment]
这个板子应该是立功科技那边拿到的吧，你应该问回立功科技那边的人，可能会更加清楚一点
