### ISSUE TITLE
thread_t 类型找不到定义

### ISSUE THREAD

**Issue by releung** [zlgopen/awtk-linux-fb#6]
linux 上交叉编译，thread_t 类型并不是 pthread_t 类型，然而并没有找到类型的定义，不能编译通过。

**Comment by releung** [comment]
找到了问题了，是这里没有及时和 https://github.com/zlgopen/awtk 同步导致。
commit 2925f4e882d576db66f14668178f98877b3dcce0
Author: lixianjing <xianjimli@hotmail.com>
Date:   Mon May 6 16:35:51 2019 +0800

    rename thread to tk_thread

**Comment by xianjimli** [comment]
已更新。谢谢。
