### ISSUE TITLE
linux-fb编译报错

### ISSUE THREAD

**Issue by WeSrc-Yin** [zlgopen/awtk-linux-fb#61]
linux-fb编译报错如下：

...
...
...
../arm-linux-gnueabihf/bin/ld: cannot find -lhal
...
/arm-linux-gnueabihf/bin/ld: cannot find -lcsv
collect2: error: ld returned 1 exit status
scons: *** [build/bin/libawtk.so] Error 1
scons: building terminated because of errors.
======================== build app ========================
...
...

**Comment by xianjimli** [comment]
awtk是最新的吗

**Comment by WeSrc-Yin** [comment]
> awtk是最新的吗

awtk是昨天拉的最新的，且scons 编译awtk源码可以编译通过。

**Comment by xianjimli** [comment]
我用最新的awtk-linux-fb和awtk测试没有发现问题。你把build目录删除，重新编译试试。

**Comment by WeSrc-Yin** [comment]
> 我用最新的awtk-linux-fb和awtk测试没有发现问题。你把build目录删除，重新编译试试。

删掉build，重新编译还是报这两个错误， -lcsv  -lhal是什么库。

**Comment by soyzhc** [comment]
这两个是awtk里面的两个模块, 看看是不是上面编译这两个代码时出错了
可以用 scons -c 清空编译再重新编译, 注意看编译log信息

**Comment by WeSrc-Yin** [comment]
> 这两个是awtk里面的两个模块, 看看是不是上面编译这两个代码时出错了
> 可以用 scons -c 清空编译再重新编译, 注意看编译log信息

由于虽然报这个错，但仍然可以跑，目前没发现啥问题，过两天得空了再查一下哪儿的问题；另外，这两个模块我可以关掉不编译吗，如果我不需要这两个模块，我就可以不变异它吧？能关掉的话怎么关掉？
