### ISSUE TITLE
应用编译出来 在imx6ul上运行出现not found

### ISSUE THREAD

**Issue by hvritual** [zlgopen/awtk-linux-fb#66]
![image](https://user-images.githubusercontent.com/11900351/124299606-35d72d80-db90-11eb-864f-688234206518.png)
![image](https://user-images.githubusercontent.com/11900351/124299751-5ef7be00-db90-11eb-8e4a-6848b63fee58.png)
![image](https://user-images.githubusercontent.com/11900351/124299848-76cf4200-db90-11eb-8852-5e47ada04a61.png)
第一图是运行信息
第二图是编译后文件ELF信息
第三图是使用的编译器

awtk-config.py 配置修改如下
TSLIB_LIB_DIR=''
TSLIB_INC_DIR=''
TOOLS_PREFIX='/root/4.9.3/bin/arm-cortexa9-linux-gnueabihf-'

**Comment by xianjimli** [comment]
1.用file查看一下demo的文件信息。
2.设置LD_LIBRARY_PATH环境变量。

**Comment by hvritual** [comment]
ok 我先试一下 谢谢

**Comment by hvritual** [comment]
编译器和imx6的LD文件不一导致
