### ISSUE TITLE
2440开发板上移植问题

### ISSUE THREAD

**Issue by whwxxstsyd** [zlgopen/awtk-linux-fb#7]
您好，我想将这款GUI移植到自己手头的一块s3c2440开发板上，但是出现了一些问题。

使用的是3.4.2内核，编译器使用的是arm-linux-gcc 4.3.2

整个工程按照说明已经编译通过，但是在开发板上运行的时候，出现了这样子的问题

/ # demoui 
app_root_is_valid:43 app_root != NULL
Illegal instruction

/bin # demo_desktop 
Illegal instruction

网上查找说是编译器的问题

但是运行tslib_test，确又可以正常输出

/ # tslib_test /dev/event0 
tslib_dispatch_one_event: e.pressure=1 x=102 y=56
pointer down:102 56
tslib_dispatch_one_event: e.pressure=1 x=102 y=56
pointer move:102 56
tslib_dispatch_one_event: e.pressure=1 x=101 y=56
pointer move:101 56

因为不是在您推荐的那款开发板上进行开发，所以编译过程中也出现很多问题，想请教一下您

这是我最开始的配置

TSLIB_LIB_DIR='/home/hetianqi/Desktop/work/software/tslib/tmp/lib'
TSLIB_INC_DIR='/home/hetianqi/Desktop/work/software/tslib/tmp/include'
TOOLS_PREFIX='/usr/local/arm/4.3.2/bin/arm-linux-'

编译报错

hetianqi@hetianqi-virtual-machine:~/Desktop/work/awtk/awtk-linux-fb$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
/usr/local/arm/4.3.2/bin/arm-linux-gcc -o awtk-port/input_dispatcher.o -c -std=gnu99 -g -Wall -Os -DHAS_STD_MALLOC -DWITH_FS_RES -DHAS_STDIO -DWITH_VGCANVAS -DWITH_UNICODE_BREAK -DLINUX -DSTBTT_STATIC -DSTB_IMAGE_STATIC -DWITH_STB_IMAGE -DWITH_STB_FONT -DWITH_NANOVG_AGGE -DWITH_WIDGET_TYPE_CHECK -DLINUX -DHAS_PTHREAD -DENABLE_CURSOR -DHAS_TSLIB -I/home/hetianqi/Desktop/work/software/tslib/tmp/include -I/home/hetianqi/Desktop/work/awtk/awtk -I/home/hetianqi/Desktop/work/awtk/awtk/src -I/home/hetianqi/Desktop/work/awtk/awtk/3rd -I/home/hetianqi/Desktop/work/awtk/awtk/src/ext_widgets -I/home/hetianqi/Desktop/work/awtk/awtk/tools -I/home/hetianqi/Desktop/work/awtk/awtk/3rd/agge -I/home/hetianqi/Desktop/work/awtk/awtk/3rd/agg/include -I/home/hetianqi/Desktop/work/awtk/awtk/3rd/nanovg -I/home/hetianqi/Desktop/work/awtk/awtk/3rd/nanovg/base -I/home/hetianqi/Desktop/work/awtk/awtk/3rd/libunibreak -I/home/hetianqi/Desktop/work/awtk/awtk/3rd/gpinyin/include awtk-port/input_dispatcher.c
/usr/local/arm/4.3.2/bin/arm-linux-gcc: line 3: exec: arm-none-linux-gnueabi-gcc: not found
scons: *** [awtk-port/input_dispatcher.o] Error 127
scons: building terminated because of errors.

后来又修改成

TSLIB_LIB_DIR='/home/hetianqi/Desktop/work/software/tslib/tmp/lib'
TSLIB_INC_DIR='/home/hetianqi/Desktop/work/software/tslib/tmp/include'
TOOLS_PREFIX='/usr/local/arm/4.3.2/bin/arm-none-linux-gnueabi-'

这才编译通过，不知道这有什么区别

问题可能有点蠢，但是确实对这款GUI非常感兴趣，希望您能帮我解答一下，感谢

**Comment by xianjimli** [comment]
1. arm-none-linux-gnueabi-gcc: not found 应该就是TOOLS_PREFIX设置不对。

2. 你对比一下生成tslib_test时的FLAGS，上次有个朋友因为-mfloat-abi=这个参数，出现类似的错误。

**Comment by whwxxstsyd** [comment]
您好，按照您的建议，对比了tslib_test的FLAGS，但并无差异，-mfloat-abi也根据平台修改为-mfloat-abi=softfp，目前使用的是4.3.2的编译器，3.4.2的内核，但是还是出现Illegal instruction错误。

**Comment by xianjimli** [comment]
去掉-mfloat-abi=softfp这个试试。

**Comment by whwxxstsyd** [comment]
去掉了-mfloat-abi=softfp，但还是无法运行，后来尝试使用GDB来调试，打印信息如下

(gdb) c
Continuing.
warning: Could not load shared library symbols for 8 libraries, e.g. /lib/libts-0.0.so.0.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?

Program received signal SIGILL, Illegal instruction.
0x000a8090 in __divsi3 ()
(gdb) info sharedlibrary
From        To          Syms Read   Shared Object Library
                        No          /lib/libts-0.0.so.0
                        No          /usr/lib/libstdc++.so.6
                        No          /lib/libpthread.so.0
                        No          /lib/libm.so.6
                        No          /lib/libdl.so.2
                        No          /lib/libgcc_s.so.1
                        No          /lib/libc.so.6
                        No          /lib/ld-linux.so.3
(gdb) n
Single stepping until exit from function __divsi3,
which has no line number information.

Program terminated with signal SIGILL, Illegal instruction.
The program no longer exists.


有点困惑

**Comment by xianjimli** [comment]
1.把divsi3的汇编代码打出来看看。

2.好像死在tslib里，去掉tslib试试。

**Comment by whwxxstsyd** [comment]
老师，后来我又使用GDB一步步调试，发现程序在初始化的时候每次都是运行到gettimeofday这里就报Illegal instruction的错误。怀疑是我链接库版本的问题，所以我单独写了一个简单的程序验证gettimeofday，但可以正常运行，没有报错。后来又发现一些标准的库函数都无法使用，之前tslib_test可以正常运行，是因为没有使用标准的一些函数。您有什么好的建议吗

**Comment by xianjimli** [comment]
确实有些奇怪。看看链接时的参数。

**Comment by whwxxstsyd** [comment]
[log.txt](https://github.com/zlgopen/awtk-linux-fb/files/3357570/log.txt)

这个是我编译的log

**Comment by xianjimli** [comment]
加这个参数试试：-mthumb-interwork

**Comment by whwxxstsyd** [comment]
之前加上了您说的参数，但是还是报错，后来我自己有捣鼓下，却又出现了不一样的错误

Breakpoint 1, main (argc=1, argv=0xbefffe84) at build/var/awtk/demos/demo_main.c:47
47        if (argc >= 2) {
(gdb) n
43      int main(int argc, char* argv[]) {
(gdb) n
47        if (argc >= 2) {
(gdb) n
65        tk_init(lcd_w, lcd_h, APP_SIMULATOR, NULL, NULL);
(gdb) s
tk_init (w=320, h=480, app_type=APP_SIMULATOR, app_name=0x0, app_root=0x0) at build/var/awtk/src/awtk_global.c:175
175     ret_t tk_init(wh_t w, wh_t h, app_type_t app_type, const char* app_name, const char* app_root) {
(gdb) s
177       return_value_if_fail(platform_prepare() == RET_OK, RET_FAIL);
(gdb) s
platform_prepare () at build/var/awtk/src/platforms/pc/platform.c:107
107       date_time_set_impl(date_time_get_now_impl);
(gdb) s
date_time_set_impl (date_time_get_now=0x3d790 <date_time_get_now_impl>) at build/var/awtk/src/tkc/date_time.c:27
27        s_date_time_get_now = date_time_get_now;
(gdb) s
30      }
(gdb) s
platform_prepare () at build/var/awtk/src/platforms/pc/platform.c:110
110     }
(gdb) s
tk_init (w=320, h=480, app_type=APP_SIMULATOR, app_name=0x0, app_root=0x0) at build/var/awtk/src/awtk_global.c:178
178       ENSURE(system_info_init(app_type, app_name, app_root) == RET_OK);
(gdb) s
system_info_init (app_type=APP_SIMULATOR, app_name=0x0, app_root=0x0) at build/var/awtk/src/base/system_info.c:108
108       if (s_system_info == NULL) {
(gdb) s
107     ret_t system_info_init(app_type_t app_type, const char* app_name, const char* app_root) {
(gdb) s
108       if (s_system_info == NULL) {
(gdb) s
109         s_system_info = system_info_create(app_type, app_name, app_root);
(gdb) s
system_info_create (app_type=APP_SIMULATOR, app_name=0x0, app_root=0x0) at build/var/awtk/src/base/system_info.c:191
191     system_info_t* system_info_create(app_type_t app_type, const char* app_name, const char* app_root) {
(gdb) s
192       object_t* obj = object_create(&s_system_info_vtable);
(gdb) s
191     system_info_t* system_info_create(app_type_t app_type, const char* app_name, const char* app_root) {
(gdb) s
192       object_t* obj = object_create(&s_system_info_vtable);
(gdb) s
object_create (vt=0xad518 <s_system_info_vtable>) at build/var/awtk/src/tkc/object.c:59
59        return_value_if_fail(vt != NULL && vt->size >= sizeof(object_t), NULL);
(gdb) s
61        obj = (object_t*)TKMEM_ALLOC(vt->size);
(gdb) s
tk_alloc (size=72, func=0xd134d <__FUNCTION__.4067> "object_create", line=61) at build/var/awtk/src/tkc/mem.c:356
356     void* tk_alloc(uint32_t size, const char* func, uint32_t line) {
(gdb) s
364         addr = tk_alloc_impl(size);
(gdb) s
tk_alloc_impl (size=72) at build/var/awtk/src/tkc/mem.c:41
41        if (size > MAX_BLOCK_SIZE) {
(gdb) s
39      static void* tk_alloc_impl(uint32_t size) {
(gdb) s
41        if (size > MAX_BLOCK_SIZE) {
(gdb) s
45        ptr = malloc(size);
(gdb) s
Cannot access memory at address 0x0

Program received signal SIGSEGV, Segmentation fault.
0xe7f001f0 in ?? ()
(gdb) 

这是我单步调试的log，这次又出现在了malloc上，同样的，我单独写的malloc可以正常使用

**Comment by whwxxstsyd** [comment]
我又试了几次还是不行，实在是水品有限，解决不了这个问题，目前怀疑是编译器的问题，对浮点支持不是非常友好，手头的这块开发板有点年头了。后来就放弃使用3.4.2内核加4.3.2的编译器组合，最后改用2.6.22.6内核加gcc-3.4.5-glibc-2.3.6的组合，awtk可以正常运行，那几个demo也基本都能运行了。但是出现问题的具体原因还是没有找到，只知道每次运行到gettimeofday就崩溃了，后来我又尝试着先去掉gettimeofday，可还是有问题


这是暂时去掉gettimeofday

#0  0x000a7d00 in __udivsi3 ()
#1  0x0007d4f4 in ime_pinyin::MatrixSearch::alloc_resource (this=0x1fe1a8)
    at build/var/awtk/3rd/gpinyin/src/matrixsearch.cpp:98
#2  0x0007d5b0 in ime_pinyin::MatrixSearch::init (this=0x1fe1a8, 
    fn_sys_dict=0xdc19f <data_gpinyin> "\a", 
    fn_usr_dict=0x13 <error: Cannot access memory at address 0x13>)
    at build/var/awtk/3rd/gpinyin/src/matrixsearch.cpp:115
#3  0x00078b14 in im_open_decoder_rom () at build/var/awtk/3rd/gpinyin/src/pinyinime.cpp:46
#4  0x0003df70 in input_engine_create ()
    at build/var/awtk/src/input_engines/input_engine_pinyin.cpp:93
#5  0x0003d8d0 in input_method_default_create ()
    at build/var/awtk/src/input_methods/input_method_default.inc:282
#6  0x0003d328 in tk_init_internal () at build/var/awtk/src/awtk_global.c:141
#7  0x0003d580 in tk_init (w=320, h=480, app_type=APP_SIMULATOR, app_name=0x0, 
    app_root=0x9dd8 <_start> "$\300\237", <incomplete sequence \345>)
    at build/var/awtk/src/awtk_global.c:179
#8  0x0000bd80 in main (argc=<optimized out>, argv=0xbefffe84)
    at build/var/awtk/demos/demo_main.c:65
Cannot access memory at address 0x0


暂时的话就先在2.6内核下开发玩玩，希望老师有空的话能帮忙看看，感谢

**Comment by xianjimli** [comment]
能用就好。
