### ISSUE TITLE
使用ubuntu环境进行测试时不显示鼠标

### ISSUE THREAD

**Issue by 18611429192** [zlgopen/awtk-linux-fb#72]
我现在没有硬件板子，所以就使用安装在virtualbox中的Ubuntu虚拟机进行测试。
我按照demoui的介绍方式编译好了，执行sudo ./release/bin/demoui后界面显示正常的，但是没有显示鼠标，这时因为什么呢？我仅修改了https://github.com/zlgopen/awtk-linux-fb中介绍的内容，其他的代码都没动。
这是因为我使用了systemctl set-default multi-user.target命令么？

**Comment by xianjimli** [comment]
确认一下宏ENABLE_CURSOR是否定义。

**Comment by 18611429192** [comment]
![image](https://user-images.githubusercontent.com/49744753/131318463-2df962e5-a526-4d5f-ad9f-21b40f321d24.png)
这个应该是定义了的

**Comment by xianjimli** [comment]
这个图片文件存在吗？default/images/x1/cursor.png

**Comment by 18611429192** [comment]
![image](https://user-images.githubusercontent.com/49744753/131320448-7a297c5e-3ee3-4035-9e45-402bd7903c42.png)
也是存在的

**Comment by xianjimli** [comment]
在window_manager_paint_cursor里打印些调试信息看看。

**Comment by 18611429192** [comment]
可以具体点么，加什么

**Comment by 18611429192** [comment]
我的鼠标只要进入虚拟机的范围就会消失，会不会是因为这个问题呢

**Comment by xianjimli** [comment]
进入虚拟机后，应该由window_manager_paint_cursor绘制鼠标，你看看有没有进入canvas_draw_icon函数。

**Comment by 18611429192** [comment]
没有调用，我加一个printf函数，，ctrl+c退出程序后没有相关的打印

**Comment by 18611429192** [comment]
![image](https://user-images.githubusercontent.com/49744753/131324983-f2b35cf0-36ca-4e69-b823-c2b1affb6239.png)
![image](https://user-images.githubusercontent.com/49744753/131325076-d3356182-81e6-4200-8de8-a644c17451fc.png)
进入这个范围随便晃了晃，点了几下，退出后没有打印this is a test!

**Comment by 18611429192** [comment]
![image](https://user-images.githubusercontent.com/49744753/131335282-95f8891a-e28d-49d4-90dc-623699c468f9.png)
换到桌面系统就能正常了，在字符模式确实哪里不对劲。

**Comment by soyzhc** [comment]
虚拟机里用awtk-linux-fb鼠标是会有些问题，VMware也一样，可能是虚拟机的鼠标捕获机制问题

**Comment by soyzhc** [comment]
编辑 awtk-port/main\_loop\_linux.c 修改输入设备的文件名
```
#define MICE_DEVICE_FILENAME "/dev/input/mouse0"
```
有些虚拟机要把mouse0 改为 mouse1，可以尝试一下
