### ISSUE TITLE
MusicPlayer.v2-Demo CPU 占用过高，到了40%

### ISSUE THREAD

**Issue by archeng320** [zlgopen/awtk-linux-fb#74]
CPU 是双核A7 1G主频， LCD使用是 fb，分辨率是1920*720，使用top 看CPU占用了40%。同一台机器，用QT软件，CPU才占用5%。请问，怎么优化CPU的使用率？

**Comment by archeng320** [comment]
Mem: 54908K used, 179264K free, 44K shrd, 320K buff, 13640K cached
CPU:  39% usr   0% sys   0% nic  60% idle   0% io   0% irq   0% sirq
Load average: 0.86 0.83 0.72 2/53 147
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  143   108 root     R    49328  21%   0  40% ./mnt/udisk/bin/demo
   20     2 root     IW       0   0%   0   0% [kworker/0:1-eve]
  147   108 root     R     2316   1%   1   0% top
  106     1 dbus     S     2380   1%   0   0% dbus-daemon --system
  108     1 root     S     2316   1%   0   0% -/bin/sh
    1     0 root     S     2196   1%   0   0% init
   82     1 root     S     2196   1%   1   0% /sbin/syslogd -n
   86     1 root     S     2196   1%   1   0% /sbin/klogd -n
   56     2 root     IW       0   0%   0   0% [kworker/u4:1-fl]
   66     2 root     SW       0   0%   1   0% [ubi_bgt0d]
   10     2 root     IW       0   0%   1   0% [rcu_sched]
   60     2 root     IW       0   0%   1   0% [kworker/1:2-eve]
  134     2 root     SW       0   0%   0   0% [usb-storage]
    9     2 root     SW       0   0%   0   0% [ksoftirqd/0]
   21     2 root     IW       0   0%   1   0% [kworker/1:1-mm_]
   16     2 root     SW       0   0%   1   0% [ksoftirqd/1]
  135     2 root     IW       0   0%   0   0% [kworker/u4:0-fl]
   15     2 root     SW       0   0%   1   0% [migration/1]
    2     0 root     SW       0   0%   0   0% [kthreadd]
    3     2 root     IW<      0   0%   0   0% [rcu_gp]

**Comment by soyzhc** [comment]
中间的转盘转动时会耗费cpu，
也可以看看你的平台是否支持drm模式，切换方法见awtk-linux-fb/readme

**Comment by soyzhc** [comment]
谢谢，我们查一下，可能是最近的版本修改的问题

**Comment by archeng320** [comment]
更新到新版软件后，简单的demo的cpu占用率降到1%，但是有动画的demo，如demo_animator ，CPU占用 17% ，不知道是否正常

**Comment by soyzhc** [comment]
正常的, 动画, 特别是旋转动画会占用cpu
47f26cbae14ed9a  本问题已修复,   请把awtk和awtk-linux-fb都更新到最新版本
