### ISSUE TITLE
linux 平台运行AWTK Designer生成的代码失败

### ISSUE THREAD

**Issue by archeng320** [zlgopen/awtk-linux-fb#79]
AWTK Designer生成的代码 在window 10上模拟运行成功，但是放到Linux上运行失败，已经更新到最新的awtk版本

日志：
try /
try set app_root:/res
try set app_root:/demos
try /mnt/udisk/bin
app_root=/mnt/udisk
fb_info_t: /dev/fb0
xres=1920 yres=720
xres_virtual=1920 yres_virtual=1440
bits_per_pixel=32 line_length=7680
fb_info_t: red(16 8) green(8 8) blue(0 8)
xpanstep=0 ywrapstep=0
fb_size=5529600 fb_total_size=16777216 fb_nr=2 smem_len=16777216
fb_open clear
fb_open ok
sh: dmidecode: not found
=========fb_number=2
ratio=1.000000 1920 720
ratio=1.000000 1920 720
tslib_run:116: open tslib successful, filename=/dev/input/event0
input_run:310: open keyboard failed, fd=-1, filename=/dev/input/event1
input_run:254: open mouse failed, fd=-1, filename=/dev/input/mouse0
Build at: Sep 28 2021 14:19:57
!!!Asset [name=uiex/sysbar_landscape type=ui] not exist!!!
ui_loader_load_widget_with_parent:46 condition(ui != NULL) failed!
!!!Asset [name=uiex/menu_landscape type=ui] not exist!!!
ui_loader_load_widget_with_parent:46 condition(ui != NULL) failed!
!!!Asset [name=uiex/preload type=ui] not exist!!!
ui_loader_load_widget_with_parent:46 condition(ui != NULL) failed!
widget_add_timer:3143 condition(widget != NULL && on_timer != NULL) failed!

**Comment by archeng320** [comment]
music demo 可以正常运行

**Comment by fatalfeel** [comment]
because resource bin data incorrect
run release.sh

tar zcvf release.tar.gz release
~copy release.tar.gz to target and in target console extract 
tar -xvf release.tar.gz
cd ./release/bin
./demoui
