### ISSUE TITLE
触摸屏使用问题

### ISSUE THREAD

**Issue by yang0311** [zlgopen/awtk-linux-fb#82]
硬件板未连接触摸屏，需要通过串口接收MCU发送的触摸屏坐标数据，那么如何将接收到的触摸屏坐标等信息转化成AWTK对应的触摸事件？

**Comment by soyzhc** [comment]
参考awtk-port/input_thread/tslib_thread.c 或mouse_thread.c 自己做一个获取触摸消息的线程，通过main_loop_post_pointer_event()把消息转发到awtk

**Comment by yang0311** [comment]
感谢支持，该功能已实现
