### ISSUE TITLE
移植awtk到安凯ak3760e板子上出现语法错误

### ISSUE THREAD

**Issue by 1234code** [zlgopen/awtk-linux-fb#94]
![微信截图_20220714112036](https://user-images.githubusercontent.com/49601846/178891033-41402d1b-e5aa-4eb6-a06f-af219c7d7150.png)
![微信截图_20220714112149](https://user-images.githubusercontent.com/49601846/178891169-9aa12423-fa6f-4c77-ad6d-c4b83b7eb368.png)
![微信截图_20220714112326](https://user-images.githubusercontent.com/49601846/178891313-0a0ddbdd-8840-4805-8c67-853260b27089.png)

**Comment by 1234code** [comment]
图1是在开发板上运行的报错
图2是编译工具链
图3是本地修改的config
请问是什么原因导致的报错？

**Comment by xianjimli** [comment]
是不是PC版本的demoui拷到板子上了。用file看看demoui是什么文件格式。

```
file demoui
```

**Comment by 1234code** [comment]
[](url)
![Uploading 微信截图_20220714112950.png…]()

**Comment by 1234code** [comment]
![微信截图_20220714112950](https://user-images.githubusercontent.com/49601846/178891983-7feb3acd-eb6e-4614-8f5d-f6abeb9a8f41.png)

**Comment by 1234code** [comment]
demoui: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=e5315a2585bf3d0f23f48a2a1b0bea2f6b84744c, not stripped
file demoui后的信息

**Comment by xianjimli** [comment]
对吧。你这个是x86的指令，板子是arm的芯片。

**Comment by 1234code** [comment]
不好意思，请问怎么修改呢？

**Comment by xianjimli** [comment]
TOOLS_PREFIX的值，貌似后面多了gcc-

**Comment by 1234code** [comment]
![image](https://user-images.githubusercontent.com/49601846/178927394-4ba97d49-65b6-4070-a6eb-29c52750b91f.png)
您好，我们将gcc-去掉之后重新编译出来的demoui还是x86的。
